/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyntheticMriRouteImport } from './routes/synthetic-mri'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as GanResearchRouteImport } from './routes/gan-research'
import { Route as ExplainableAiRouteImport } from './routes/explainable-ai'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'

const SyntheticMriRoute = SyntheticMriRouteImport.update({
  id: '/synthetic-mri',
  path: '/synthetic-mri',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const GanResearchRoute = GanResearchRouteImport.update({
  id: '/gan-research',
  path: '/gan-research',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainableAiRoute = ExplainableAiRouteImport.update({
  id: '/explainable-ai',
  path: '/explainable-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/explainability': typeof ExplainabilityRoute
  '/explainable-ai': typeof ExplainableAiRoute
  '/gan-research': typeof GanResearchRoute
  '/methodology': typeof MethodologyRoute
  '/research': typeof ResearchRoute
  '/synthetic-mri': typeof SyntheticMriRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/explainability': typeof ExplainabilityRoute
  '/explainable-ai': typeof ExplainableAiRoute
  '/gan-research': typeof GanResearchRoute
  '/methodology': typeof MethodologyRoute
  '/research': typeof ResearchRoute
  '/synthetic-mri': typeof SyntheticMriRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/explainability': typeof ExplainabilityRoute
  '/explainable-ai': typeof ExplainableAiRoute
  '/gan-research': typeof GanResearchRoute
  '/methodology': typeof MethodologyRoute
  '/research': typeof ResearchRoute
  '/synthetic-mri': typeof SyntheticMriRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/explainability'
    | '/explainable-ai'
    | '/gan-research'
    | '/methodology'
    | '/research'
    | '/synthetic-mri'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/explainability'
    | '/explainable-ai'
    | '/gan-research'
    | '/methodology'
    | '/research'
    | '/synthetic-mri'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/explainability'
    | '/explainable-ai'
    | '/gan-research'
    | '/methodology'
    | '/research'
    | '/synthetic-mri'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  ExplainableAiRoute: typeof ExplainableAiRoute
  GanResearchRoute: typeof GanResearchRoute
  MethodologyRoute: typeof MethodologyRoute
  ResearchRoute: typeof ResearchRoute
  SyntheticMriRoute: typeof SyntheticMriRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/synthetic-mri': {
      id: '/synthetic-mri'
      path: '/synthetic-mri'
      fullPath: '/synthetic-mri'
      preLoaderRoute: typeof SyntheticMriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gan-research': {
      id: '/gan-research'
      path: '/gan-research'
      fullPath: '/gan-research'
      preLoaderRoute: typeof GanResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainable-ai': {
      id: '/explainable-ai'
      path: '/explainable-ai'
      fullPath: '/explainable-ai'
      preLoaderRoute: typeof ExplainableAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  ExplainableAiRoute: ExplainableAiRoute,
  GanResearchRoute: GanResearchRoute,
  MethodologyRoute: MethodologyRoute,
  ResearchRoute: ResearchRoute,
  SyntheticMriRoute: SyntheticMriRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
